services:
    _defaults:
        autowire: true
        autoconfigure: true


    MangoSylius\MailChimpPlugin\Service\:
        resource: '../../Service/*'

    mangosylius.mailchimp_plugin.service.channel_mailchimp_settings_provider:
        class: MangoSylius\MailChimpPlugin\Service\ChannelMailChimpSettingsProvider
        arguments:
            $channelContext: '@sylius.context.channel.request_based'

    MangoSylius\MailChimpPlugin\Service\MailChimpChannelSubscriber:
        arguments:
            $shopperContext: '@sylius.context.shopper'
            $channelMailChimpSettingsProvider: '@mangosylius.mailchimp_plugin.service.channel_mailchimp_settings_provider'

    MangoSylius\MailChimpPlugin\Model\CustomerListener:
        arguments:
            $channelMailChimpSettingsProvider: '@mangosylius.mailchimp_plugin.service.channel_mailchimp_settings_provider'
        tags:
            -  { name: kernel.event_listener, event: sylius.customer.post_create, method: syncSubscriptionToMailChimp }
            -  { name: kernel.event_listener, event: sylius.customer.post_update, method: syncSubscriptionToMailChimp }
            -  { name: kernel.event_listener, event: security.interactive_login, method: syncSubstriptionStateFromMailChimp }

    MangoSylius\MailChimpPlugin\Repository\ChannelMailChimpSettingsRepository:
        class: MangoSylius\MailChimpPlugin\Repository\ChannelMailChimpSettingsRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - MangoSylius\MailChimpPlugin\Entity\ChannelMailChimpSettings

    MangoSylius\MailChimpPlugin\Form\Extension\MailChimpChannelTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\ChannelBundle\Form\Type\ChannelType }

    Sylius\Bundle\UiBundle\Block\BlockEventListener:
        arguments:
            - '@@SyliusMailChimpPlugin\channelForm.html.twig'
        tags:
            -
                name: kernel.event_listener
                event: sonata.block.event.sylius.admin.channel
                method: onBlockEvent
