MangoSylius\MailChimpPlugin\Entity\ChannelMailChimpSettings:
    type: entity
    table: mangosylius_channel_mailchimp_settings
    repositoryClass: MangoSylius\MailChimpPlugin\Repository\ChannelMailChimpSettingsRepository
    id:
        channel:
            associationKey: true

    fields:
        isMailChimpEnabled:
            column: is_mailchimp_enabled
            type: boolean
            unique: false
            nullable: false
        mailChimpListId:
            column: mailchimp_list_id
            type: string
            unique: false
            nullable: true
        isMailChimpListDoubleOptInEnabled:
            column: is_mailchimp_list_double_optin_enabled
            type: boolean
            unique: false
            nullable: false

    oneToOne:
        channel:
            targetEntity: Sylius\Component\Core\Model\Channel
            cascade: ["persist"]
